<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>apttest</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<style>
    .rad{
        padding= 6px;
    }
</style>
</head>

<body>

<nav class="navbar navbar-expand-md bg-dark navbar-dark">
  <!-- Brand -->
  <a class="navbar-brand" href="Homepage.php">Logo</a>

  <!-- Toggler/collapsibe Button -->
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon"></span>
  </button>

  <!-- Navbar links -->
  <div class="collapse navbar-collapse" id="collapsibleNavbar">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link active" href="about.php">About</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="faq.php">FAQ</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="contact.php">Contact Us</a>
      </li>
    </ul>
  </div>
</nav>
<div class="jumbotron">
<h1 class="display-4">Aptitude Test</h1>
<hr>
</div>
<u><h2 style="margin:3px;">Instructions:</h2></u><br>
<p style="margin:5px;">This quiz contains 10 questions which you are supposed to solve through programming.
  All the best!! </p>
<hr>
<br>
<h3 style="margin:3px;">Questions:</h3></u><br>


<form action="qa.php" method="POST">
    <b>1.</b> If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.

<br>Find the sum of all the multiples of 3 or 5 below 1000. <br><br>
 <div class="rad">
<input type="radio" name="ans1" value="233165"> 233165<br>
<input type="radio" name="ans1" value="233167"> 233167<br>
<input type="radio" name="ans1" value="233168"> 233168<br>
<input type="radio" name="ans1" value="233166"> 233166<br>
</div>
   <br><br>
    <b>2.</b>   Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: <br>

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...<br>

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.<br><br>
<div class="rad">
<input type="radio" name="ans2" value="4613731"> 4613731<br>
<input type="radio" name="ans2" value="4613732"> 4613732<br>
<input type="radio" name="ans2" value="4613733"> 4613733<br>
<input type="radio" name="ans2" value="4613734"> 4613734<br>
</div>
   <br><br>
    <b>3.</b>   The prime factors of 13195 are 5, 7, 13 and 29.<br>

What is the largest prime factor of the number 600851475143 ?<br><br>
<div class="rad">
<input type="radio" name="ans3" value="6857"> 6857<br>
<input type="radio" name="ans3" value="6856"> 6856<br>
<input type="radio" name="ans3" value="6855"> 6855<br>
<input type="radio" name="ans3" value="6854"> 6854<br>
</div>
   <br><br>
    <b>4.</b>  The sum of the primes below 10 is 2 + 3 + 5 + 7 = 17.

Find the sum of all the primes below two million.<br><br>
<div class="rad">
<input type="radio" name="ans4" value="142913828925"> 142913828925<br>
<input type="radio" name="ans4" value="142913828922"> 142913828922<br>
<input type="radio" name="ans4" value="142913828927"> 142913828927<br>
<input type="radio" name="ans4" value="142913828921"> 142913828921<br>
</div>
   <br><br>
    <b>5.</b>  By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13.

What is the 10001st prime number?<br><br>
<div class="rad">
<input type="radio" name="ans5" value="104749"> 104749<br>
<input type="radio" name="ans5" value="104747"> 104747<br>
<input type="radio" name="ans5" value="104745"> 104745<br>
<input type="radio" name="ans5" value="104743"> 104743<br>
</div>
   <br><br>
    <b>6.</b>  Surprisingly there are only three numbers that can be written as the sum of fourth powers of their digits:<br><br>

1634 = 1<sup>4</sup> + 6<sup>4</sup> + 3<sup>4</sup> + 4<sup>4</sup><br>
8208 = 8<sup>4</sup> + 2<sup>4</sup> + 0<sup>4</sup> + 8<sup>4</sup><br>
9474 = 9<sup>4</sup> + 4<sup>4</sup> + 7<sup>4</sup> + 4<sup>4</sup><br><br>


As 1 = 1<sup>4</sup> is not a sum it is not included.

The sum of these numbers is 1634 + 8208 + 9474 = 19316.

Find the sum of all the numbers that can be written as the sum of fifth powers of their digits.<br><br>
<div class="rad">
<input type="radio" name="ans6" value="443836"> 443836<br>
<input type="radio" name="ans6" value="443837"> 443837<br>
<input type="radio" name="ans6" value="443838"> 443838<br>
<input type="radio" name="ans6" value="443839"> 443839<br>
</div>
   <br><br>
    <b>7.</b>  The sum of the squares of the first ten natural numbers is,<br>

12 + 22 + ... + 102 = 385<br>
The square of the sum of the first ten natural numbers is,<br>

(1 + 2 + ... + 10)2 = 552 = 3025<br>
Hence the difference between the sum of the squares of the first ten natural numbers and the square of the sum is 3025 − 385 = 2640.<br>

Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum.<br><br>
<div class="rad">
<input type="radio" name="ans7" value="25164120"> 25164120<br>
<input type="radio" name="ans7" value="25164140"> 25164140<br>
<input type="radio" name="ans7" value="25164150"> 25164150<br>
<input type="radio" name="ans7" value="25164190"> 25164190<br>
</div>
   <br><br>
    <b>8.</b>  n! means n × (n − 1) × ... × 3 × 2 × 1<br>

For example, 10! = 10 × 9 × ... × 3 × 2 × 1 = 3628800,<br>
and the sum of the digits in the number 10! is 3 + 6 + 2 + 8 + 8 + 0 + 0 = 27.<br>

Find the sum of the digits in the number 100!<br><br>
<div class="rad">
<input type="radio" name="ans8" value="481"> 481<br>
<input type="radio" name="ans8" value="648"> 648<br>
<input type="radio" name="ans8" value="743"> 743<br>
<input type="radio" name="ans8" value="593"> 593<br>
</div>
   <br><br>
    <b>9.</b>The series, 1<sup>1</sup> + 2<sup>2</sup> + 3<sup>3</sup> + ... + 10<sup>10</sup> = 10405071317.<br>

Find the last ten digits of the series, 1<sup>1</sup> + 2<sup>3</sup> + 3<sup>3</sup> + ... + 1000<sup>1000</sup>.<br><br>
<div class="rad">
<input type="radio" name="ans9" value="9110846700"> 9110846700<br>
<input type="radio" name="ans9" value="9110846700"> 8130848900<br>
<input type="radio" name="ans9" value="9110846700"> 7110842500<br>
<input type="radio" name="ans9" value="9110846700"> 8130849700<br>
</div>
   <br><br>
    <b>10.</b> 145 is a curious number, as 1! + 4! + 5! = 1 + 24 + 120 = 145.<br>

Find the sum of all numbers which are equal to the sum of the factorial of their digits.<br>

<b>Note:</b> as 1! = 1 and 2! = 2 are not sums they are not included.<br><br>
<div class="rad">
<input type="radio" name="ans10" value="40250"> 40250<br>
<input type="radio" name="ans10" value="40330"> 40330<br>
<input type="radio" name="ans10" value="40560"> 40560<br>
<input type="radio" name="ans10" value="40730"> 40730<br>
 </div>

<br><br>
<p align="center"><input class="btn btn-primary" type="submit" name="submit" value="Submit"></p>
 </form>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
</body>
</html>
